POST http://localhost:3333/videos

{
  "title": "Video 01",
  "description": "Video react do Casimiro",
  "duration": 180 
}

### 
GET http://localhost:3333/videos


### 
GET http://localhost:3333/videos?search

### 
PUT http://localhost:3333/videos/:id
{
  "title": "Video 01",
  "description": "Video react do Casimiro",
  "duration": 180 
}

### 
DELETE http://localhost:3333/videos/:id